---
ID: "6c769710-f89f-49db-af64-1b50ef6ec7a0"
Parent: "ace30b66-4af7-4afa-afa8-6c70128080c8"
Template: "ace30b66-4af7-4afa-afa8-6c70128080c8"
Path: /sitecore/templates/User Defined/Food Type/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180903T103716Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
