---
ID: "f3787cbb-817a-42d8-abc5-65dfdd4cb803"
Parent: "c819e51c-c750-4e2a-8699-f68260e35565"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/User Defined/Product/Product Details/ProductName
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180903T105153Z
